foreground            #ffffff
background            #08080d
selection_background  #e60026
cursor                #e60026

# Основные ANSI-цвета под стилистику
color0  #08080d
color8  #303036
color1  #e60026
color9  #ff3b5c
color2  #34d399
color10 #a7f3d0
color3  #fcd34d
color11 #fef08a
color4  #e60026
color12 #ff3b5c
color5  #ffffff
color13 #fbcfe8
color6  #22d3ee
color14 #99f6e4
color7  #ffffff
color15 #ffffff
