# --- Cosmic/Mahiru Kitty Config ---

# Цветовая схема
foreground            #E0E7FF
background            #050A14
selection_foreground  #050A14
selection_background  #3B82F6

# Основные цвета (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
color0  #050A14
color8  #475569

# Акцентные цвета (звездное свечение и синий космос)
color2  #3B82F6
color10 #60A5FA
color3  #FCD34D
color11 #FDE68A

# Остальные цвета (адаптированы под общую гамму)
color1  #EF4444
color9  #F87171
color4  #22D3EE
color12 #67E8F9
color5  #C084FC
color13 #E9D5FF
color6  #3B82F6
color14 #60A5FA
color7  #E0E7FF
color15 #FFFFFF

# Прозрачность
background_opacity 0.7
dynamic_background_opacity yes

# Курсор
cursor                #3B82F6
cursor_text_color     #050A14

# Настройки шрифта
font_size            12.0

# Убираем рамки окна
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0
shell_integration disabled

# Remote control & layout
allow_remote_control yes
listen_on unix:/tmp/mykitty
map ctrl+shift+w toggle_layout stack

# BEGIN_KITTY_FONTS
font_family      family="DejaVu Sans Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS