# === Цветовая схема под черно-красные обои «Yukiaim» ===
foreground            #ffffff
background            #08080d
selection_foreground  #08080d
selection_background  #e60026

# Прозрачность (сохранил твои 0.7)
background_opacity 0.7
dynamic_background_opacity yes

# Курсор (неоново-красный, в цвет глаз девочки)
cursor                #e60026
cursor_text_color     #08080d

# Основная палитра (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
# Черный (обсидиановые тени)
color0  #08080d
color8  #303036

# Красный / Кровавый (основной акцент)
color1  #e60026
color9  #ff3b5c

# Зеленый (приглушенный холодный изумруд)
color2  #10b981
color10 #34d399

# Желтый (мягкий золотой)
color3  #f59e0b
color11 #fbbf24

# Синий (холодная сталь)
color4  #3b82f6
color12 #60a5fa

# Маджента / Фиолетовый (заменен на контрастный белый/серебряный)
color5  #ffffff
color13 #e2e8f0

# Циан (холодный неоновый лед)
color6  #06b6d4
color14 #22d3ee

# Белый (кристально чистый)
color7  #e2e8f0
color15 #ffffff


# === Твои настройки и шрифты ===
font_size        12.0

# Убираем рамки окна (для Hyprland)
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0
shell_integration disabled

# Бинды и ресайз
allow_remote_control yes
listen_on unix:/tmp/mykitty
map ctrl+shift+w toggle_layout stack

# BEGIN_KITTY_FONTS
font_family      family="DejaVu Sans Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
