# BACKGROUND
background {
    monitor =
    path = ~/wallpaper/black_hyprlock.png
    blur_passes = 0
}

# PROFIE-PHOTO
image {
    monitor =
    path = ~/.config/hypr/vivek.png
    border_size = 2
    border_color = rgba(230, 0, 38, 0.80) # Неоново-красная рамка
    size = 120
    rounding = -1
    position = 0, 200
    halign = center
    valign = center
}

# NAME
label {
    monitor =
    text = ym1co
    color = rgba(255, 255, 255, 0.80) # Чистый белый цвет
    font_size = 24
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 120
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(255, 255, 255, 0.80)
    font_size = 60
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 40
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(242, 242, 247, 0.80) # Мягкий серебряный звездный свет
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -10
    halign = center
    valign = center
}

# INPUT FIELD (Поле ввода пароля)
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(e60026) # Ярко-красный неоновый контур
    inner_color = rgb(08080d) # Обсидиановый черный фон
    font_color = rgb(ffffff)  # Белые точки пароля
    placeholder_text = <i>Password...</i>
    position = 0, -100
    halign = center
    valign = center
}
