# Общие настройки (вне блоков)
preload = /home/ym1co/wallpaper/black_wallpaper.jpg

wallpaper = HDMI-A-1,/home/ym1co/wallpaper/black_wallpaper.jpg
wallpaper = DP-1,/home/ym1co/wallpaper/black_wallpaper.jpg
