# BACKGROUND
background {
    monitor =
    path = ~/wallpaper/hyprlock.png
    blur_passes = 0
}

# PROFIE-PHOTO
image {
    monitor =
    path = ~/.config/hypr/vivek.png
    border_size = 2
    border_color = rgba(216, 222, 233, 0.80)
    size = 120
    rounding = -1
    position = 0, 200
    halign = center
    valign = center
}

# NAME (Убрал смещение по X, чтобы было ровно по центру)
label {
    monitor =
    text = ym1co
    color = rgba(216, 222, 233, 0.80)
    font_size = 24
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 120
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%H:%M")</span>"
    color = rgba(216, 222, 233, 0.80)
    font_size = 60
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, 40
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgba(216, 222, 233, .80)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -10
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(C084FC)
    inner_color = rgb(141026)
    font_color = rgb(E2DAF5)
    placeholder_text = <i>Password...</i>
    position = 0, -100
    halign = center
    valign = center
}
