# === Цветовая схема под пиксельные обои ===
foreground            #E2DAF5
background            #0F0B21
selection_foreground  #0F0B21
selection_background  #C084FC

# Прозрачность (оставил твои 0.7, с этим фоном будет пушка)
background_opacity 0.7
dynamic_background_opacity yes

# Курсор (неоново-сиреневый, в цвет кроны дерева)
cursor                #D187F5
cursor_text_color     #0F0B21

# Основная палитра (Black, Red, Green, Yellow, Blue, Magenta, Cyan, White)
# Черный (глубокие тени)
color0  #0F0B21
color8  #433563

# Красный / Розовый (закат на горизонте)
color1  #BF306A
color9  #F0438A

# Зеленый (приглушенная ночная трава)
color2  #3E7D65
color10 #5FE0b5

# Желтый (теплый свет из окон домика)
color3  #E39E30
color11 #FCD34D

# Синий (ночное небо)
color4  #3D47A8
color12 #5664f5

# Маджента / Фиолетовый (светящиеся листья)
color5  #824CA6
color13 #C084FC

# Циан (светлые звезды)
color6  #3F8EA3
color14 #5CE1E6

# Белый (цвет облаков)
color7  #C2B6DE
color15 #F3F0FA


# === Твои настройки и шрифты ===
font_size        12.0

# Убираем рамки окна (для Hyprland)
window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0
shell_integration disabled

# Бинды и ресайз
allow_remote_control yes
listen_on unix:/tmp/mykitty
map ctrl+shift+w toggle_layout stack

# BEGIN_KITTY_FONTS
font_family      family="DejaVu Sans Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
