# Основные цвета (Фон взят из самого темного участка неба/травы, текст — из светлых звезд)
foreground            #e2daf5
background            #0f0b21
selection_background  #58378a
cursor                #d187f5

# Обычные цвета (Low-intensity)
color0  #0f0b21
color1  #bf306a
color2  #479177
color3  #e39e30
color4  #3d47a8
color5  #824ca6
color6  #3f8ea3
color7  #c2b6de

# Яркие цвета (High-intensity акценты)
color8  #433563
color9  #f0438a
color10 #5fe0b5
color11 #fcd34d
color12 #5664f5
color13 #c084fc
color14 #5ce1e6
color15 #f3f0fa
